from __future__ import annotations

from datetime import datetime
from typing import Protocol

from quackit.models import (
    MemoryCreate,
    MemoryRecord,
    MemoryUpdate,
    ProjectRecord,
    SearchResult,
    SessionRecord,
    SkillCreate,
    SkillRecord,
    SkillUpdate,
)


class StorageBackend(Protocol):
    def close(self) -> None: ...
    def create_project(self, name: str, description: str | None = None) -> ProjectRecord: ...
    def get_project(self, project_id: str) -> ProjectRecord | None: ...
    def list_projects(self) -> list[ProjectRecord]: ...
    def consolidate_projects(self, source_ids: list[str], target_id: str) -> ProjectRecord: ...
    def create_session(self, project_id: str | None = None) -> SessionRecord: ...
    def list_recent_sessions(self, limit: int = 10) -> list[SessionRecord]: ...
    def get_session(self, session_id: str) -> SessionRecord | None: ...
    def end_session(self, session_id: str, summary: str) -> SessionRecord: ...
    def update_session_heartbeat(self, session_id: str) -> None: ...
    def list_stale_open_sessions(self, since: datetime) -> list[SessionRecord]: ...
    def orphan_session(self, session_id: str, summary: str) -> SessionRecord: ...
    def save_memory(self, session_id: str, memory: MemoryCreate) -> MemoryRecord: ...
    def get_memory(self, mem_id: str) -> MemoryRecord | None: ...
    def count_memories(self, session_id: str) -> int: ...
    def update_memory(self, mem_id: str, update: MemoryUpdate) -> MemoryRecord: ...
    def search_memories(
        self,
        session_id: str,
        query: str,
        memory_type: str | None,
        content_type: str | None = None,
        limit: int = 100,
    ) -> list[SearchResult]: ...
    def search_memories_by_project(
        self,
        project_id: str,
        query: str,
        memory_type: str | None,
        content_type: str | None = None,
        limit: int = 100,
    ) -> list[SearchResult]: ...
    def list_sessions_by_project(self, project_id: str) -> list[SessionRecord]: ...
    def save_skill(self, skill: SkillCreate) -> SkillRecord: ...
    def get_skill(self, skill_id: str) -> SkillRecord | None: ...
    def update_skill(self, skill_id: str, update: SkillUpdate) -> SkillRecord: ...
    def delete_skill(self, skill_id: str) -> None: ...
    def list_skills(self, query: str = "", tag: str | None = None) -> list[SkillRecord]: ...
